### ISSUE TITLE
Publicly exposed Vuplex 3D WebView

### ISSUE THREAD

**Issue by binarynate** [puddleglum56/wemspace#1]
Hi, @puddleglum56 👋. This is Nate, the Founder of Vuplex. First, thanks again for using 3D WebView! I really appreciate your business. I'm opening this issue because your repo includes the assets for 3D WebView, which aren't allowed to be shared publicly according to its license. To resolve this issue, can you please make the repository private?

https://github.com/puddleglum56/wemspace/tree/6c7c8393598e91cacc0a3e7857cdbdace24b11d0/Assets/Vuplex/WebView

**Comment by puddleglum56** [comment]
Yup! Switched to private.
